name = "NavierStokesPaper"
version = "0.1.0"
defaultTargets = ["NavierStokesPaper"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5352afccd6866369be9de43f5b7ec47203555f44"

[[require]]
name = "LeanCert"
git = "https://github.com/alerad/leancert.git"
rev = "b3eaaaea63b752a23e519d424d1187988cd3f301"

[[lean_lib]]
name = "Phase0_Analysis"
srcDir = "Lean"

[[lean_lib]]
name = "Phase1_Foundation"
srcDir = "Lean"

[[lean_lib]]
name = "Phase2_Operators"
srcDir = "Lean"

[[lean_lib]]
name = "Phase3_Isomorphism"
srcDir = "Lean"

[[lean_lib]]
name = "Phase4_Regularity"
srcDir = "Lean"

[[lean_lib]]
name = "NavierStokes_Core"
srcDir = "Lean"

[[lean_lib]]
name = "Phase2_Projection"
srcDir = "Lean"

[[lean_lib]]
name = "Phase3_Advection"
srcDir = "Lean"

[[lean_lib]]
name = "NavierStokes_Master"
srcDir = "Lean"

[[lean_lib]]
name = "Phase5_Equivalence"
srcDir = "Lean"

[[lean_lib]]
name = "Phase6_Cauchy"
srcDir = "Lean"

[[lean_lib]]
name = "Phase7_Density"
srcDir = "Lean"

[[lean_lib]]
name = "Validation"
srcDir = "Lean"

[[lean_lib]]
name = "NavierStokesPaper"
srcDir = "Lean"
globs = ["Phase0_Analysis", "Phase1_Foundation", "Phase2_Operators", "Phase3_Isomorphism", "Phase4_Regularity", "NavierStokes_Core", "Phase2_Projection", "Phase3_Advection", "NavierStokes_Master", "Phase5_Equivalence", "Phase6_Cauchy", "Phase7_Density", "Validation"]
